Public Class BordersStorePage

    Dim border As Integer = 4
    Dim price As Integer = 0
    Dim currency As String = "Gold"

    Private Sub ListBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ListBox1.SelectedIndexChanged
        If ListBox1.SelectedItem = "Blue Border" Then
            border = 4
            price = 900
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "Green Border" Then
            border = 5
            price = 900
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "Red Border" Then
            border = 6
            price = 900
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "Cyan Border" Then
            border = 7
            price = 70
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Blue-Eyes White Dragon" Then
            border = 16
            price = 5100
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "5ds Border" Then
            border = 17
            price = 290
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Exodia the Forbidden One" Then
            border = 18
            price = 10000
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "United States of America" Then
            border = 19
            price = 34000
            currency = "Gold"
        ElseIf ListBox1.SelectedItem = "The Seal of Orichalcos" Then
            border = 20
            price = 110
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Millennium Border" Then
            border = 21
            price = 400
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Water Border II" Then
            border = 62
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Alexis Border" Then
            border = 31
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "ARC-V Border" Then
            border = 32
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Akiza Border" Then
            border = 33
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Akiza Border II" Then
            border = 34
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Chazz Border" Then
            border = 35
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Crow Border" Then
            border = 36
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "The Green Leaf" Then
            border = 37
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "The Fire Border" Then
            border = 38
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Gundam Border" Then
            border = 39
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "The Star" Then
            border = 71
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Ancient Bird" Then
            border = 72
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "GX Border" Then
            border = 40
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Jack Border" Then
            border = 42
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Jaden Border" Then
            border = 43
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Jesse Border" Then
            border = 44
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Ninja Border" Then
            border = 49
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Regi Border" Then
            border = 50
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "The Rose Border" Then
            border = 51
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Hatsune Miku" Then
            border = 52
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Hatsune Miku II" Then
            border = 53
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Hatsune Miku III" Then
            border = 54
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Kaiba Border" Then
            border = 55
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Shark Border" Then
            border = 56
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Leo Border" Then
            border = 57
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Sora Border" Then
            border = 58
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Susanoo Border" Then
            border = 60
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Venam Border" Then
            border = 613
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yugo Border" Then
            border = 64
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yugi Border" Then
            border = 65
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yusei Border" Then
            border = 66
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuya Border" Then
            border = 67
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuri Border I" Then
            border = 76
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuri Border II" Then
            border = 77
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Zane Border" Then
            border = 68
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Zexal Border" Then
            border = 69
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "The Colorful Border" Then
            border = 70
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Hata no Kokoro Border I" Then
            border = 78
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Hata no Kokoro Border II" Then
            border = 79
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "PowerPuff Girls Border" Then
            border = 80
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Reimu Hakurei Border I" Then
            border = 81
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Reimu Hakurei Border II" Then
            border = 82
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Sakuya Izayoi Border I" Then
            border = 83
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Sakuya Izayoi Border II" Then
            border = 84
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Totally Spies Border" Then
            border = 85
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Bakura Border I" Then
            border = 86
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Bakura Border II" Then
            border = 87
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border I" Then
            border = 88
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border II" Then
            border = 89
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border III" Then
            border = 90
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border IV" Then
            border = 91
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border V" Then
            border = 92
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Christmas Border VI" Then
            border = 93
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Ishizu Border I" Then
            border = 94
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Ishizu Border II" Then
            border = 95
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Lazar Border" Then
            border = 96
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Mai Border I" Then
            border = 97
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Mai Border II" Then
            border = 98
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Mai Border III" Then
            border = 99
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Mako Border" Then
            border = 100
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Marik Border I" Then
            border = 101
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Marik Border II" Then
            border = 102
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Odion Border" Then
            border = 103
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Pegasus Border" Then
            border = 104
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Reji Border" Then
            border = 105
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Thief King Border I" Then
            border = 106
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Thief King Border II" Then
            border = 107
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yori Border" Then
            border = 108
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yubel Border" Then
            border = 109
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yami Border I" Then
            border = 110
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yami Border II" Then
            border = 111
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yami Border III" Then
            border = 112
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yami Border IV" Then
            border = 113
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yami Border V" Then
            border = 114
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yugo Border" Then
            border = 115
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yusei Border I" Then
            border = 116
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yusei Border II" Then
            border = 117
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuto Border I" Then
            border = 118
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuto Border II" Then
            border = 119
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Yuto Border III" Then
            border = 120
            price = 300
            currency = "Diamonds"
        ElseIf ListBox1.SelectedItem = "Pinkie Pie Border" Then
            border = 122
            price = 300
            currency = "Diamonds"
        End If

        Try
            PictureBox1.Image = Image.FromFile(Launcher.Current & "\YGOPRO\textures\borders\" & border & ".png")
            PictureBox2.Image = Image.FromFile(Launcher.Current & "\YGOPRO\textures\borders\" & border & " 2.png")

            borderNameLbl.Text = "Border: " & ListBox1.SelectedItem
            priceLbl.Text = price

            If currency = "Gold" Then
                gold.BringToFront()
            Else
                diamonds.BringToFront()
            End If
        Catch
        End Try
    End Sub

    Private Sub BordersStorePage_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Try
            PictureBox1.Image = Image.FromFile(Launcher.Current & "\YGOPRO\textures\borders\" & border & ".png")
            PictureBox2.Image = Image.FromFile(Launcher.Current & "\YGOPRO\textures\borders\" & border & " 2.png")
        Catch
        End Try
    End Sub

    Private Sub buyButton_Click(sender As Object, e As EventArgs) Handles buyButton.Click
        Launcher.SendToServer("Buy<{]>Border<{]>" & border)
    End Sub
End Class
