'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("YGOPRO_The_Dawn_of_a_New_Era_Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arcr1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcr1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arcr2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcr2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blank_Item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blank_Item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_Red_Eyes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue_Red_Eyes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChatB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChatC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChatC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ChatG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChatG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConclaveC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConclaveC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConclaveC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConclaveC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeckC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeckC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeckC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeckC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DecksB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DecksB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DecksG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DecksG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Default_Private_Chat_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Default_Private_Chat_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelingRobotB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelingRobotB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DuelingRobotR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DuelingRobotR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FacebookB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FacebookB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FacebookG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FacebookG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HomeC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomeC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HomeC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HomeC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AdBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AdBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AdBlockH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AdBlockH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AmethystMembership() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AmethystMembership", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AmethystMembershipH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AmethystMembershipH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Avatar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Avatar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AvatarCardBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AvatarCardBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AvatarCardBackH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AvatarCardBackH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_AvatarH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_AvatarH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_BlueChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_BlueChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_BlueChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_BlueChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_BoldChatFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_BoldChatFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_BoldChatFontH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_BoldChatFontH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CardBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CardBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CardBackH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CardBackH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ChangeUsername() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ChangeUsername", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ChangeUsernameH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ChangeUsernameH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ChatBundle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ChatBundle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ChatBundleH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ChatBundleH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ClassifiedAccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ClassifiedAccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ClassifiedAccessH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ClassifiedAccessH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomBorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomBorderH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomBorderH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomFontH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomFontH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomPrivateChat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomPrivateChat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomPrivateChatH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomPrivateChatH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomTextColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomTextColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomTextColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomTextColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomTitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomTitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomTitleH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomTitleH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomUsernameColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomUsernameColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_CustomUsernameColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_CustomUsernameColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DiamondMembership() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DiamondMembership", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DiamondMembershipH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DiamondMembershipH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DuelLuna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DuelLuna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DuelLunaH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DuelLunaH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DuelSetoKaiba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DuelSetoKaiba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_DuelSetoKaibaH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_DuelSetoKaibaH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_FBIChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_FBIChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_FBIChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_FBIChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Firelord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Firelord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_FirelordH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_FirelordH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GoldMembership() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GoldMembership", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GoldMembershipH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GoldMembershipH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GoldSarcophagus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GoldSarcophagus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GoldSarcophagusH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GoldSarcophagusH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GreenChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GreenChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_GreenChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_GreenChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ItalicChatFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ItalicChatFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ItalicChatFontH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ItalicChatFontH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LordOfLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LordOfLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_LordOfLightH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_LordOfLightH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_MeCommand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_MeCommand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_MeCommandH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_MeCommandH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Nightshade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Nightshade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_NightshadeH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_NightshadeH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_PinkChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_PinkChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_PinkChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_PinkChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_PlatinumMembership() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_PlatinumMembership", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_PlatinumMembershipH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_PlatinumMembershipH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_RainbowChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_RainbowChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_RainbowChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_RainbowChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_RedChatColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_RedChatColor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_RedChatColorH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_RedChatColorH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ResetWP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ResetWP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_ResetWPH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_ResetWPH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Rexterra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Rexterra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_RexterraH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_RexterraH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Starcaller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Starcaller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_StarcallerH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_StarcallerH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Stormborn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Stormborn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_StormbornH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_StormbornH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_StrikeoutChatFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_StrikeoutChatFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_StrikeoutChatFontH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_StrikeoutChatFontH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TDOANEChallenge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TDOANEChallenge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TDOANEChallengeH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TDOANEChallengeH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TeamMembersBonus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TeamMembersBonus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TeamMembersBonusH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TeamMembersBonusH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TeamQuote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TeamQuote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TeamQuoteH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TeamQuoteH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_Tidemaster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_Tidemaster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TidemasterH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TidemasterH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TournamentHosting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TournamentHosting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_TournamentHostingH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_TournamentHostingH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_UnblockRanked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_UnblockRanked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_UnblockRankedH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_UnblockRankedH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_UnderlineChatFont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_UnderlineChatFont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Item_UnderlineChatFontH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Item_UnderlineChatFontH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LargeMysteryBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LargeMysteryBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LargeMysteryBoxSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LargeMysteryBoxSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MysteryBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MysteryBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property News1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property News2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property News3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property News4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property News5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewsB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewsB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewsG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewsG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OptionsB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OptionsG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelDraw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelDraw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelLose0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelLose0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelLose1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelLose1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelLose2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelLose2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelWin0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelWin0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelWin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelWin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property postDuelWin2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postDuelWin2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProfileB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfileB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProfileC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfileC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProfileC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfileC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProfileG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProfileG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PuzzlesB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PuzzlesB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PuzzlesR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PuzzlesR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PvPB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PvPB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PvPR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PvPR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Qualified1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qualified1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Qualified2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qualified2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Qualified3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Qualified3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RankedB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RankedB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RankedBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RankedBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RankedR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RankedR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Red_Red_Eyes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_Red_Eyes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReplaysB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplaysB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReplaysC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplaysC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReplaysC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplaysC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReplaysG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplaysG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SinglePlayerB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SinglePlayerB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SinglePlayerR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SinglePlayerR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillTestsB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillTestsB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SkillTestsR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SkillTestsR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StoreB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StoreB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StoreC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StoreC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StoreC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StoreC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StoreG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StoreG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SupportG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SupportG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SupportR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SupportR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TeamC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TeamC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TeamC_HL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TeamC_HL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TeamsB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TeamsB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TeamsG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TeamsG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TournamentB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TournamentB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TournamentR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TournamentR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TwitterB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwitterB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TwitterG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TwitterG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnrankedB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnrankedB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnrankedBanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnrankedBanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnrankedR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnrankedR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property W1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("W1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
