'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Accounts() As String
            Get
                Return CType(Me("Accounts"),String)
            End Get
            Set
                Me("Accounts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ToS() As String
            Get
                Return CType(Me("ToS"),String)
            End Get
            Set
                Me("ToS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AutoRefresh() As String
            Get
                Return CType(Me("AutoRefresh"),String)
            End Get
            Set
                Me("AutoRefresh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("English")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Other() As String
            Get
                Return CType(Me("Other"),String)
            End Get
            Set
                Me("Other") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SavedUsername() As String
            Get
                Return CType(Me("SavedUsername"),String)
            End Get
            Set
                Me("SavedUsername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SavedPassword() As String
            Get
                Return CType(Me("SavedPassword"),String)
            End Get
            Set
                Me("SavedPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SavedCheck() As String
            Get
                Return CType(Me("SavedCheck"),String)
            End Get
            Set
                Me("SavedCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FilterGames() As String
            Get
                Return CType(Me("FilterGames"),String)
            End Get
            Set
                Me("FilterGames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Link1() As String
            Get
                Return CType(Me("Link1"),String)
            End Get
            Set
                Me("Link1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Link2() As String
            Get
                Return CType(Me("Link2"),String)
            End Get
            Set
                Me("Link2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Link3() As String
            Get
                Return CType(Me("Link3"),String)
            End Get
            Set
                Me("Link3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Link4() As String
            Get
                Return CType(Me("Link4"),String)
            End Get
            Set
                Me("Link4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Link5() As String
            Get
                Return CType(Me("Link5"),String)
            End Get
            Set
                Me("Link5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DUC() As String
            Get
                Return CType(Me("DUC"),String)
            End Get
            Set
                Me("DUC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DRC() As String
            Get
                Return CType(Me("DRC"),String)
            End Get
            Set
                Me("DRC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")>  _
        Public Property Background() As Global.System.Drawing.Color
            Get
                Return CType(Me("Background"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Background") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property TypeText() As Global.System.Drawing.Color
            Get
                Return CType(Me("TypeText"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TypeText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property Search() As Global.System.Drawing.Color
            Get
                Return CType(Me("Search"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Search") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property Userlist() As Global.System.Drawing.Color
            Get
                Return CType(Me("Userlist"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Userlist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Brown")>  _
        Public Property Owner() As Global.System.Drawing.Color
            Get
                Return CType(Me("Owner"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Owner") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property Administrator() As Global.System.Drawing.Color
            Get
                Return CType(Me("Administrator"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Administrator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Green")>  _
        Public Property GlobalModerator() As Global.System.Drawing.Color
            Get
                Return CType(Me("GlobalModerator"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GlobalModerator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property Moderator() As Global.System.Drawing.Color
            Get
                Return CType(Me("Moderator"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Moderator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Teal")>  _
        Public Property Bot() As Global.System.Drawing.Color
            Get
                Return CType(Me("Bot"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Bot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Goldenrod")>  _
        Public Property GoldMember() As Global.System.Drawing.Color
            Get
                Return CType(Me("GoldMember"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GoldMember") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property PlatinumMember() As Global.System.Drawing.Color
            Get
                Return CType(Me("PlatinumMember"),Global.System.Drawing.Color)
            End Get
            Set
                Me("PlatinumMember") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property Player() As Global.System.Drawing.Color
            Get
                Return CType(Me("Player"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Player") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Magenta")>  _
        Public Property System() As Global.System.Drawing.Color
            Get
                Return CType(Me("System"),Global.System.Drawing.Color)
            End Get
            Set
                Me("System") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HotPink")>  _
        Public Property EventManager() As Global.System.Drawing.Color
            Get
                Return CType(Me("EventManager"),Global.System.Drawing.Color)
            End Get
            Set
                Me("EventManager") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FCO() As String
            Get
                Return CType(Me("FCO"),String)
            End Get
            Set
                Me("FCO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MCO() As String
            Get
                Return CType(Me("MCO"),String)
            End Get
            Set
                Me("MCO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property STS() As String
            Get
                Return CType(Me("STS"),String)
            End Get
            Set
                Me("STS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property UDX() As String
            Get
                Return CType(Me("UDX"),String)
            End Get
            Set
                Me("UDX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property US() As String
            Get
                Return CType(Me("US"),String)
            End Get
            Set
                Me("US") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property AA() As String
            Get
                Return CType(Me("AA"),String)
            End Get
            Set
                Me("AA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FS() As String
            Get
                Return CType(Me("FS"),String)
            End Get
            Set
                Me("FS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MIGS() As String
            Get
                Return CType(Me("MIGS"),String)
            End Get
            Set
                Me("MIGS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ACP() As String
            Get
                Return CType(Me("ACP"),String)
            End Get
            Set
                Me("ACP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property RCP() As String
            Get
                Return CType(Me("RCP"),String)
            End Get
            Set
                Me("RCP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ACO() As String
            Get
                Return CType(Me("ACO"),String)
            End Get
            Set
                Me("ACO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property NDFC() As String
            Get
                Return CType(Me("NDFC"),String)
            End Get
            Set
                Me("NDFC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Volume() As String
            Get
                Return CType(Me("Volume"),String)
            End Get
            Set
                Me("Volume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MyLastCode() As String
            Get
                Return CType(Me("MyLastCode"),String)
            End Get
            Set
                Me("MyLastCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property TextColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("TextColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TextColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property MuteChat() As String
            Get
                Return CType(Me("MuteChat"),String)
            End Get
            Set
                Me("MuteChat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property FBI() As Global.System.Drawing.Color
            Get
                Return CType(Me("FBI"),Global.System.Drawing.Color)
            End Get
            Set
                Me("FBI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property NRun() As Integer
            Get
                Return CType(Me("NRun"),Integer)
            End Get
            Set
                Me("NRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DTC() As String
            Get
                Return CType(Me("DTC"),String)
            End Get
            Set
                Me("DTC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property showTeam() As Boolean
            Get
                Return CType(Me("showTeam"),Boolean)
            End Get
            Set
                Me("showTeam") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property showTitle() As Boolean
            Get
                Return CType(Me("showTitle"),Boolean)
            End Get
            Set
                Me("showTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property DiamondMember() As Global.System.Drawing.Color
            Get
                Return CType(Me("DiamondMember"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DiamondMember") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ChatMessages() As Integer
            Get
                Return CType(Me("ChatMessages"),Integer)
            End Get
            Set
                Me("ChatMessages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DVE() As String
            Get
                Return CType(Me("DVE"),String)
            End Get
            Set
                Me("DVE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ColoredMessages() As Boolean
            Get
                Return CType(Me("ColoredMessages"),Boolean)
            End Get
            Set
                Me("ColoredMessages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultDeck() As String
            Get
                Return CType(Me("DefaultDeck"),String)
            End Get
            Set
                Me("DefaultDeck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ShowPostDuelMessages() As Integer
            Get
                Return CType(Me("ShowPostDuelMessages"),Integer)
            End Get
            Set
                Me("ShowPostDuelMessages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("215, 40, 106")>  _
        Public Property Curator() As Global.System.Drawing.Color
            Get
                Return CType(Me("Curator"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Curator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("215, 40, 106")>  _
        Public Property DefaultCurator() As Global.System.Drawing.Color
            Get
                Return CType(Me("DefaultCurator"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DefaultCurator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AdDisplayed() As Date
            Get
                Return CType(Me("AdDisplayed"),Date)
            End Get
            Set
                Me("AdDisplayed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property pmType() As String
            Get
                Return CType(Me("pmType"),String)
            End Get
            Set
                Me("pmType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AMCP() As Integer
            Get
                Return CType(Me("AMCP"),Integer)
            End Get
            Set
                Me("AMCP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ASTCP() As Integer
            Get
                Return CType(Me("ASTCP"),Integer)
            End Get
            Set
                Me("ASTCP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property MusicVolume() As Integer
            Get
                Return CType(Me("MusicVolume"),Integer)
            End Get
            Set
                Me("MusicVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property SoundVolume() As Integer
            Get
                Return CType(Me("SoundVolume"),Integer)
            End Get
            Set
                Me("SoundVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property enableMusic() As Integer
            Get
                Return CType(Me("enableMusic"),Integer)
            End Get
            Set
                Me("enableMusic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property enableSound() As Integer
            Get
                Return CType(Me("enableSound"),Integer)
            End Get
            Set
                Me("enableSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property showAdvertisements() As Boolean
            Get
                Return CType(Me("showAdvertisements"),Boolean)
            End Get
            Set
                Me("showAdvertisements") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property showDuelingRobotBetaWarning() As Boolean
            Get
                Return CType(Me("showDuelingRobotBetaWarning"),Boolean)
            End Get
            Set
                Me("showDuelingRobotBetaWarning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TCG")>  _
        Public Property hostBanlist() As String
            Get
                Return CType(Me("hostBanlist"),String)
            End Get
            Set
                Me("hostBanlist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TCG/OCG")>  _
        Public Property hostAllowedCards() As String
            Get
                Return CType(Me("hostAllowedCards"),String)
            End Get
            Set
                Me("hostAllowedCards") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Single Duel")>  _
        Public Property hostDuelMode() As String
            Get
                Return CType(Me("hostDuelMode"),String)
            End Get
            Set
                Me("hostDuelMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property hostDontRecoverTime() As Boolean
            Get
                Return CType(Me("hostDontRecoverTime"),Boolean)
            End Get
            Set
                Me("hostDontRecoverTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property hostDontShuffleDeck() As Boolean
            Get
                Return CType(Me("hostDontShuffleDeck"),Boolean)
            End Get
            Set
                Me("hostDontShuffleDeck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HostDontCheckDeck() As Boolean
            Get
                Return CType(Me("HostDontCheckDeck"),Boolean)
            End Get
            Set
                Me("HostDontCheckDeck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8000")>  _
        Public Property hostStartingLP() As Integer
            Get
                Return CType(Me("hostStartingLP"),Integer)
            End Get
            Set
                Me("hostStartingLP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property hostStartingHand() As Integer
            Get
                Return CType(Me("hostStartingHand"),Integer)
            End Get
            Set
                Me("hostStartingHand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property hostCardsPerDraw() As Integer
            Get
                Return CType(Me("hostCardsPerDraw"),Integer)
            End Get
            Set
                Me("hostCardsPerDraw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SessionStatus() As String
            Get
                Return CType(Me("SessionStatus"),String)
            End Get
            Set
                Me("SessionStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Rule 5 (April 2020)")>  _
        Public Property hostMasterRules() As String
            Get
                Return CType(Me("hostMasterRules"),String)
            End Get
            Set
                Me("hostMasterRules") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ShowPostDuelDeckMessages() As Integer
            Get
                Return CType(Me("ShowPostDuelDeckMessages"),Integer)
            End Get
            Set
                Me("ShowPostDuelDeckMessages") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.YGOPRO_The_Dawn_of_a_New_Era_Launcher.My.MySettings
            Get
                Return Global.YGOPRO_The_Dawn_of_a_New_Era_Launcher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
